network:
  rpc: ""
  private_key: ""
  vault_address: "https://127.0.0.1:8200"
  vault_mount_path: "secret_data"
  address: "0x111"

log:
  level: debug
  disable_sentry: true

listener:
  addr: :8000

db:
  url: ""

core:
  addr: tcp://127.0.0.1:26657

cosmos:
  addr: 127.0.0.1:9090
  enable_tls: false

evm:
  chains:
    - name: ""
      bridge_address: ""
      submitter_private_key: ""
      rpc:

autorelayer:
  catchup_disabled: true
  source_contract: 0x33232 # update

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: voting-relayer
  service_port: 80
